# Generated by Django 5.0.1 on 2024-01-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birim',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='birim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.birim'),
        ),
    ]
